name: bert-ids
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy>=1.21.0
  - pandas>=1.4.0
  - scipy>=1.8.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - jupyter
  - jupyterlab
  - scikit-learn>=1.1.0
  - pytorch>=1.12.0
  - torchvision
  - torchaudio
  - cudatoolkit=11.6  # Adjust based on your CUDA version
  - pip:
    - transformers>=4.20.0
    - tensorboard>=2.9.0
    - wandb>=0.12.0
    - mlflow>=1.26.0
    - scapy>=2.4.5
    - netaddr>=0.8.0
    - pyshark>=0.5.3
    - tqdm>=4.64.0
    - pyyaml>=6.0
    - python-dotenv>=0.20.0
    - click>=8.1.0
    - pytest>=7.1.0
    - pytest-cov>=3.0.0
    - black>=22.3.0
    - flake8>=4.0.0
    - isort>=5.10.0
    - numba>=0.56.0
    - joblib>=1.1.0
    - plotly>=5.8.0
    - ipywidgets>=7.7.0
    - graphviz>=0.20.0
    - networkx>=2.8.0